### ISSUE TITLE
✨ [Feature] 마이페이지 구현하기

### ISSUE THREAD

**Issue by Austin-Choi** [5-ReBook/ReBook_FE#19]
### Description

사용자의 정보를 보여주고 수정할 수 있는 마이페이지를 구현합니다.
##
상세 요구사항
- 메인 콘텐츠 오른쪽 위에 내 정보와 보안 탭을 토글할 수 있는 스위치가 있어야 합니다.
- 내 정보 탭에는 프로필 사진, 닉네임, 대학교, 관심 전공이 나열되어 있습니다.
- 보안 탭에는 비밀번호 수정과 로그아웃, 회원 탈퇴가 있습니다.
## 
내 정보 탭
- 프로필 사진을 누르면 사진 수정 / 사진 삭제 메뉴가 팝업으로 나타납니다.
- 닉네임 수정 칸 버튼을 누르면 저장가능하고 alert창으로 저장되었다고 사용자에게 알려줍니다.
- 대학교는 수정 칸 버튼을 누르면 페이지가 뜹니다.
- 대학교 수정 페이지에서는 위에는 검색창이 있고 아래에 스크롤 가능한 창에 학교 리스트를 보여줍니다.
- 학교를 선택하고 수정하기를 누르면 모달창이 내려가고 사용자에게 저장되었다고 알려줍니다.
- 관심 전공 수정 칸 버튼을 누르면 페이지로 이동합니다.
- 상단에는 현재 저장된 관심 전공들을 버튼 형식으로 보여줍니다.
- 버튼을 누르면 해당 전공을 삭제할 수 있습니다.
- 전공 검색 칸에 검색어를 입력하면 해당하는 전공을 스크롤 가능한 창에 리스트를 보여줍니다.
- 수정하기를 누르면 나열된 버튼 데이터를 기준으로 저장하고 사용자에게 저장되었다고 알려줍니다.
##
보안 탭
- 비밀번호 수정 칸 버튼을 누르면 비밀번호 찾기 페이지로 이동합니다.
- 아래에 로그아웃 버튼(일반 공용 버튼)이 있습니다.
- 아래에 회원 탈퇴 버튼(빨간색에 흰색 텍스트)이 있습니다.

### Todo

- [x] 메인 컨텐츠 오른쪽 위에 내 정보와 보안 토글 스위치 추가
- [x] 프로필 사진 수정/삭제 기능 구현하기
- [x] 닉네임 수정 기능 구현하기
- [x] 대학교 수정 페이지 구현하기
- [x] 관심 전공 수정 페이지 구현하기
- [x] 비밀번호 수정 기능 구현하기
- [x] 로그아웃 버튼/기능 구현하기
- [x] 회원 탈퇴 버튼/기능 구현하기
