### ISSUE TITLE
🔨 [Refactoring] 채팅 페이지 버그 수정 

### ISSUE THREAD

**Issue by Austin-Choi** [5-ReBook/ReBook_FE#80]
### Description
QA 결과 참조해서 채팅 관련 페이지를 수정합니다.

20. 채팅 상품 헤더에 닉네임 있어도 이메일로 표기됨
21. 채팅 입력창이 푸터에 가려짐
22. 채팅 리스트에 사용자 이름이 아니라 상품이름이 뜨게 하는게 나을듯
23. 채팅에서 헤더 뒤로가기 버튼으로 수정
24. 웹소켓 생명주기 수정

### Todo

- [x] ChatRoomPage에서 사용자 이름 닉네임 없을 때만 이메일로 표기하기
- [x] ChatRoomPage에서 창 세로 94%로 조정
- [ ] ChatRoomListPage에서 사용자 이름 대신 상품 이름으로 교체
- [x] 채팅 관련 페이지에서 헤더 뒤로가기 버튼으로 수정
- [x] 채팅방에서 채팅 리스트로 뒤로 돌아가기 버튼을 눌렀을 때 connecting state에 있다고 나오는 문제 해결하기
