### ISSUE TITLE
🔨 [Refactoring] QA에서 발생한 문제들 리팩토링

### ISSUE THREAD

**Issue by namkikim0718** [5-ReBook/ReBook_FE#82]
### Description

- 상품 쪽에서 자잘한 문제들이 여러개 있어서 그부분들을 수정해야 합니다.

### Todo

- [x] 상품 등록시 가격이 숫자가아니면 아예 입력이 안되도록 수정
- [x] 상품 상세페이지 판매자 프로필 없으면 기본 이미지로 수정
- [x] 상품 상태 변경이 이루어지지 않던 문제 수정
- [x] 상품 수정 시 이미지 추가 없이 완료하면 처리되지 않는 문제 수정
- [x] 상품 등록 및 수정 페이지에 마이페이지처럼 선택하는 방식으로 수정
- [x] 상품 삭제 기능 추가
- [x] 페이지네이션 offset 방식 변경에 따른 프론트 로직 수정
